allowBuilds:
  '@biomejs/biome': true
  argon2: true
  esbuild: true
  msgpackr-extract: set this to true or false
  unrs-resolver: true

onlyBuiltDependencies:
  - '@biomejs/biome'
  - argon2
  - esbuild
  - unrs-resolver
